import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";
import Nav from "@/components/global/nav";
import TopBar from "@/components/global/topBar";
import { Footer } from "@/components/global/footer";
import Cta from "@/components/global/cta";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${dmSans.variable} overflow-x-hidden w-screen ${geistMono.variable} bg-gray-100 antialiased`}
      >
        <Provider>
          <div className="sticky z-50 top-0">
            <TopBar />
            <Nav />
          </div>
          <div className="w-full min-h-[50vh]">{children}</div>
          <Cta />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
