version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: abshar
      MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      app-network:
        aliases:
          - mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      app-network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: abshar777/shopco_backend_2:latest
    container_name: shopco_backend_container
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 8000
      FRONTEND_URL: https://studioivory.art
      ADMIN_URL: https://admin.studioivory.art
      MONGO_URI: mongodb://abshar:123@mongo:27017/shop-co?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: admin
      JWT_REFRESH_SECRET: 8590026442@Abshar*
      JWT_TOKEN: 8590026442@Abshar*
      JWT_ACCESS_SECRET: 8590026442@Abshar*
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
   
  admin:
    image: abshar777/admin_shopco:latest
    container_name: admin_shopco_container
    restart: on-failure
    ports:
      - "3001:3001"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      PORT: 3001
      NEXTAUTH_SECRET: "JUtN0lgNz+xCtfC/uuCx+djZb7HfIUNVyJaBIpjwFnA="
      NEXT_PUBLIC_BACKEND_URL: https://api.studioivory.art
      NEXT_PUBLIC_FRONTEND_URL: https://admin.studioivory.art
    networks:
      - app-network

  client:
    image: abshar777/client_shopco:latest
    container_name: client_shopco_container
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      PORT: 3000
      NEXTAUTH_SECRET: "JUtN0lgNz+xCtfC/uuCx+djZb7HfIUNVyJaBIpjwFnA="
      NEXT_PUBLIC_BACKEND_URL: https://api.studioivory.art
      NEXT_PUBLIC_FRONTEND_URL: https://studioivory.art
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
